---
- name: Renaming directories
  ansible.builtin.debug:
    msg: "Renaming directories"

- name: Renaming directories
  shell: "mv {{ final_template_folder }}/{{component}} {{ final_template_folder }}/{{component}}"

